#!/bin/bash

# Ensure dependencies are downloaded.
mkdir -p frontend/deps
[ ! -f "frontend/deps/xterm.js" ] && \
  wget https://cdn.jsdelivr.net/npm/xterm@5.3.0/lib/xterm.js -O frontend/deps/xterm.js
[ ! -f "frontend/deps/xterm.css" ] && \
  wget https://cdn.jsdelivr.net/npm/xterm@5.3.0/css/xterm.css -O frontend/deps/xterm.css
[ ! -f "frontend/deps/xterm-addon-fit.js" ] && \
  wget https://cdn.jsdelivr.net/npm/xterm-addon-fit@0.8.0/lib/xterm-addon-fit.js -O frontend/deps/xterm-addon-fit.js

# Release build
if [[ "$1" == "release" ]]; then
  VER=v$(date '+%y.%m').$(git rev-parse --short HEAD~5 | xxd -r -p | base64)
  set -x
  mkdir -p builds/arch
  GOARCH=arm GOARM=5 GOOS=linux go build -ldflags "-X main.version=$VER" -o builds/arch/webshush-raspberry-pi
  GOARCH=arm64 GOOS=android go build -ldflags "-X main.version=$VER" -o builds/arch/webshush-android
  GOARCH=arm64 GOOS=darwin go build -ldflags "-X main.version=$VER" -o builds/arch/webshush-macos-apple
  GOARCH=amd64 GOOS=darwin go build -ldflags "-X main.version=$VER" -o builds/arch/webshush-macos-intel
  GOARCH=amd64 GOOS=linux go build -ldflags "-X main.version=$VER" -o builds/arch/webshush-linux-x64
  GOARCH=386 GOOS=linux go build -ldflags "-X main.version=$VER" -o builds/arch/webshush-linux-x86
  GOARCH=arm64 GOOS=linux go build -ldflags "-X main.version=$VER" -o builds/arch/webshush-linux-arm
  GOARCH=riscv64 GOOS=linux go build -ldflags "-X main.version=$VER" -o builds/arch/webshush-linux-riscv
  set +x
  echo
  echo "RELEASE: $VER"
  echo "===================="
  ls -1 builds/webshush-*
fi

# Standard build
go build -o builds/webshush
